DROP DATABASE IF EXISTS biblioteca;
CREATE DATABASE biblioteca;
USE biblioteca;

CREATE TABLE SOCIOS(
	NOMBRE VARCHAR(20) NOT NULL,
	DIRECCION VARCHAR(30),
	NUMERO_TELEFONO VARCHAR(15),
	FECHA_INSCRIPCION DATE,
	N_SOCIO INT AUTO_INCREMENT,
	CONSTRAINT PK_SOCIOS PRIMARY KEY (N_SOCIOS)
);

CREATE TABLE LIBROS (
	TITULO VARCHAR(30) NOT NULL,
	AUTOR VARCHAR(20),
	FECHA_EDITADO DATE,
	N_LIBRO BIGINT AUTO_INCREMENT,
	CONSTRAINT PK_LIBROS PRIMARY KEY(N_LIBROS)
);

CREATE TABLE PRESTAMOS (
	FECHA_RETIRO DATE,
	FECHA_ENTREGA DATE,
	N_SOCIO INT,
	N_LIBRO BIGINT,
	IDPRESTAMOS BIGINT AUTOINCREMENT,
	CONSTRAINT PK_PRESTAMOS PRIMARY KEY (IDPRESTAMOS)
);

ALTER TABLE PRESTAMOS ADD CONSTRAINT FK_SOCIOS FOREIGN KEY (N_SOCIO) REFERENCES SOCIO(N_SOCIO);
ALTER TABLE PRESTAMOS ADD CONSTRAINT FK_LIBROS FOREIGN KEY (N_LIBRO) REFERENCES SOCIO(N_LIBRO);

INSERT INTO SOCIOS (NOMBRE, DIRRECION, NUMERO_TELEFONO, FECHA_INSCRIPCION) VALUES 
	('PEDRO GIL', 'CANELONES', '123.456.789', '1984-12-12'),
	('JOSE M. FORO', 'MONTEVIDEO', '987.654.321', '1997-03-02'),
	('ELBA LAZO', 'LAS PIEDRAS', '666.777.888', '2000-06-02'),
	('MARTA CANA', 'MONTEVIDEO', '600.200.200', '1999-08-15'),
